### ISSUE TITLE
No services

### ISSUE THREAD

**Issue by grosch** [vapor-community/CSRF#11]
I'm getting an error that "No services are available for 'CSRF' when I follow your installation instructions.

**Comment by 0xTim** [comment]
Have you added `services.register(CSRF())`?

**Comment by grosch** [comment]
@0xTim Nope.  Wasn't sure how to do it.  So it's basically two steps then?

```swift
services.register(CSRF())
middlewares.use(CSRF.self)
```

I found that not doing the services and instead doing `middlewards.use(CSRF())` seemed to work as well.  Can you explain the difference between the two?

**Comment by 0xTim** [comment]
Yeah that’s the two steps (it’s sneakily hidden right in the top of the code block in the README).

Basically with the code above, the first line registers the `CSRF` type to the services so that when the router is being built and goes to retrieve `CSRF.self` it knows what to use. What you’ve done is effectively the same thing in one line, the router will use `CSRF()` (an object) instead of the type, so it doesn’t need to look it up.

The reason for the difference is that you may want to register a middleware that uses the same instance across all event loops, of have a seperate instance for each event loop (avoids having to deal with thread safety). Make sense?

**Comment by grosch** [comment]
I’m sure the instructions were updated after my post. That’s my story and I’m sticking to it 😁
